# Generated by Django 5.2.1 on 2025-05-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CogEditor', '0004_remove_application_role_application_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование правила')),
                ('description', models.TextField(verbose_name='Описание правила')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет выполнения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('condition_type', models.CharField(choices=[('date_compare', 'Сравнение дат'), ('role_check', 'Проверка роли'), ('text_length', 'Длина текста'), ('combined', 'Комбинированное условие')], max_length=20, verbose_name='Тип условия')),
                ('days_threshold', models.IntegerField(blank=True, null=True, verbose_name='Порог дней')),
                ('role_id', models.IntegerField(blank=True, null=True, verbose_name='ID роли')),
                ('min_text_length', models.IntegerField(blank=True, null=True, verbose_name='Минимальная длина текста')),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CogEditor.agreedstatus', verbose_name='Новый статус')),
            ],
            options={
                'verbose_name': 'правило',
                'verbose_name_plural': 'правила',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
