# Generated by Django 5.2.1 on 2025-05-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0005_alter_application_subm_date'),
        ('CogSolver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='role_id',
        ),
        migrations.AddField(
            model_name='rule',
            name='role_id',
            field=models.ManyToManyField(blank=True, null=True, to='CogEditor.participatoryrole', verbose_name='ID роли'),
        ),
    ]
