# Generated by Django 5.2.1 on 2025-05-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogSolver', '0004_alter_rule_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Приоритет выполнения'),
        ),
    ]
