# Generated by Django 5.2.1 on 2025-05-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogSolver', '0005_alter_rule_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationSettings',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'change_status_on_classify',
                    models.BooleanField(
                        default=True,
                        verbose_name='Изменять статус при классификации',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Настройка классификации',
                'verbose_name_plural': 'Настройки классификации',
            },
        ),
    ]
