# Generated by Django 5.2.1 on 2025-05-08 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgreedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipatoryRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='StructuralUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subm_date', models.DateTimeField(verbose_name='submission date')),
                ('e_start_time', models.DateTimeField(verbose_name='Event start time')),
                ('e_end_time', models.DateTimeField(verbose_name='Event end time')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CogEditor.agreedstatus')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CogEditor.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CogEditor.employeeposition'),
        ),
        migrations.CreateModel(
            name='Contingent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_participants', models.IntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CogEditor.participatoryrole')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='structural_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CogEditor.structuralunit'),
        ),
    ]
