# Generated by Django 5.2.1 on 2025-05-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreedstatus',
            options={'ordering': ['status'], 'verbose_name': 'статус согласования', 'verbose_name_plural': 'Статусы согласования'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['subm_date'], 'verbose_name': 'заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'verbose_name': 'сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employeeposition',
            options={'ordering': ['position'], 'verbose_name': 'должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='participatoryrole',
            options={'ordering': ['role'], 'verbose_name': 'роль участника', 'verbose_name_plural': 'Роли участников'},
        ),
        migrations.AlterModelOptions(
            name='structuralunit',
            options={'ordering': ['unit'], 'verbose_name': 'структурное подразделение', 'verbose_name_plural': 'Структурные подразделения'},
        ),
        migrations.AddField(
            model_name='application',
            name='e_description',
            field=models.TextField(default='Некоторое описание мероприятия', max_length=512, verbose_name='Описание мероприятия'),
        ),
        migrations.AddField(
            model_name='application',
            name='e_title',
            field=models.TextField(default='Некоторое наименование мероприятия', max_length=256, verbose_name='Наименование мероприятия'),
        ),
        migrations.AddField(
            model_name='application',
            name='number_of_participants',
            field=models.IntegerField(default=25, verbose_name='Количество участников мероприятия'),
        ),
        migrations.AddField(
            model_name='application',
            name='role',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='CogEditor.participatoryrole', verbose_name='Роль участника мероприятия'),
        ),
        migrations.AlterField(
            model_name='agreedstatus',
            name='description',
            field=models.TextField(max_length=512, verbose_name='Описание статуса согласования'),
        ),
        migrations.AlterField(
            model_name='agreedstatus',
            name='status',
            field=models.CharField(max_length=32, verbose_name='Наименование статуса согласования'),
        ),
        migrations.AlterField(
            model_name='application',
            name='e_end_time',
            field=models.DateTimeField(verbose_name='Дата и время окончания мероприятия'),
        ),
        migrations.AlterField(
            model_name='application',
            name='e_start_time',
            field=models.DateTimeField(verbose_name='Дата и время начала мероприятия'),
        ),
        migrations.AlterField(
            model_name='application',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CogEditor.employee', verbose_name='Организатор мероприятия'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CogEditor.agreedstatus', verbose_name='Статус согласования мероприятия'),
        ),
        migrations.AlterField(
            model_name='application',
            name='subm_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации заявки'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=64, verbose_name='ФИО сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CogEditor.employeeposition', verbose_name='Должность сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='structural_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CogEditor.structuralunit', verbose_name='Структурное подразделение'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='position',
            field=models.CharField(max_length=32, verbose_name='Наименование должности'),
        ),
        migrations.AlterField(
            model_name='participatoryrole',
            name='description',
            field=models.TextField(max_length=512, verbose_name='Описание роли участника'),
        ),
        migrations.AlterField(
            model_name='participatoryrole',
            name='role',
            field=models.CharField(default='Некоторая роль', max_length=64, verbose_name='Роль участника мероприятия'),
        ),
        migrations.AlterField(
            model_name='structuralunit',
            name='unit',
            field=models.CharField(max_length=128, verbose_name='Наименование структурного подразделения'),
        ),
        migrations.DeleteModel(
            name='Contingent',
        ),
    ]
