# Generated by Django 5.2.1 on 2025-05-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0004_remove_application_role_application_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='subm_date',
            field=models.DateTimeField(verbose_name='Время регистрации заявки'),
        ),
    ]
