# Generated by Django 5.2.1 on 2025-05-11 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0005_alter_application_subm_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='organizer_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CogEditor.employee', verbose_name='Ответственный за организацию'),
        ),
        migrations.AlterField(
            model_name='application',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CogEditor.structuralunit', verbose_name='Организатор'),
        ),
    ]
