# Generated by Django 5.2.1 on 2025-05-11 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0006_application_organizer_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование приказа')),
                ('date', models.DateField(verbose_name='Дата приказа')),
                ('number', models.CharField(max_length=10, verbose_name='Номер приказа')),
            ],
            options={
                'verbose_name': 'приказ',
                'verbose_name_plural': 'Приказы',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CogEditor.order', verbose_name='Приказ на мероприятие'),
        ),
    ]
