# Generated by Django 5.2.1 on 2025-05-11 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0007_order_application_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('description', models.TextField(max_length=512, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'формат',
                'verbose_name_plural': 'Форматы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='e_description',
            field=models.TextField(max_length=512, null=True, verbose_name='Описание мероприятия'),
        ),
        migrations.AlterField(
            model_name='application',
            name='e_title',
            field=models.TextField(max_length=256, verbose_name='Наименование мероприятия'),
        ),
        migrations.AddField(
            model_name='application',
            name='e_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CogEditor.eventformat', verbose_name='Формат мероприятия'),
        ),
    ]
