# Generated by Django 5.2.1 on 2025-05-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0008_eventformat_alter_application_e_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='audio_training_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обучения работе со звуком'),
        ),
        migrations.AddField(
            model_name='application',
            name='requires_technical_support',
            field=models.BooleanField(default=False, verbose_name='Требуется техническое сопровождение'),
        ),
        migrations.AddField(
            model_name='application',
            name='technical_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Технические требования'),
        ),
    ]
