# Generated by Django 5.2.1 on 2025-05-11 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0009_application_audio_training_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('end', models.DateTimeField(verbose_name='Окончание')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='e_end_time',
        ),
        migrations.RemoveField(
            model_name='application',
            name='e_start_time',
        ),
        migrations.AddField(
            model_name='application',
            name='event_schedule',
            field=models.ManyToManyField(blank=True, related_name='event_applications', to='CogEditor.schedule', verbose_name='Время бронирования'),
        ),
        migrations.AddField(
            model_name='application',
            name='installation_deinstallation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installation_applications', to='CogEditor.schedule', verbose_name='Время монтажа/демонтажа'),
        ),
    ]
