# Generated by Django 5.2.1 on 2025-05-11 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0010_schedule_remove_application_e_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['start'], 'verbose_name': 'расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterField(
            model_name='application',
            name='installation_deinstallation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installation_applications', to='CogEditor.schedule', verbose_name='Время монтажа/демонтажа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
    ]
