# Generated by Django 5.2.1 on 2025-05-11 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0012_employee_email_employee_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Наименование источника')),
            ],
            options={
                'verbose_name': 'источник получения заявки',
                'verbose_name_plural': 'Источники получения заявок',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CogEditor.order', verbose_name='Приказ на мероприятие'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='application',
            name='application_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CogEditor.sources', verbose_name='Способ получения'),
        ),
    ]
