# Generated by Django 5.2.1 on 2025-05-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0013_sources_alter_application_order_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='e_description',
            field=models.TextField(max_length=2048, null=True, verbose_name='Описание мероприятия'),
        ),
    ]
