# Generated by Django 5.2.1 on 2025-05-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0014_alter_application_e_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventformat',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='participatoryrole',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание роли участника'),
        ),
    ]
