# Generated by Django 5.2.1 on 2025-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0015_alter_eventformat_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='ФИО сотрудника'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='position',
            field=models.CharField(max_length=32, unique=True, verbose_name='Наименование должности'),
        ),
        migrations.AlterField(
            model_name='participatoryrole',
            name='role',
            field=models.CharField(default='Некоторая роль', max_length=64, unique=True, verbose_name='Роль участника мероприятия'),
        ),
        migrations.AlterField(
            model_name='structuralunit',
            name='unit',
            field=models.CharField(max_length=128, unique=True, verbose_name='Наименование структурного подразделения'),
        ),
    ]
