# Generated by Django 5.2.1 on 2025-05-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0016_alter_employee_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Наименование источника'),
        ),
    ]
