# Generated by Django 5.2.1 on 2025-06-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CogEditor', '0018_schedule_all_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='technical_requirements',
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name='Технические требования',
            ),
        ),
    ]
