# Generated by Django 5.2.1 on 2025-06-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='phone',
            field=models.CharField(
                blank=None,
                null=None,
                unique=True,
                verbose_name='Номер телефона',
            ),
        ),
    ]
